version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=tacosjhonny
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
