# Generated by Django 4.2 on 2024-03-10 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('presupuesto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripción', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('notas', models.CharField(max_length=500)),
                ('reporte', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Listo'), (4, 'Entregado')])),
                ('total', models.FloatField()),
                ('monto_total', models.FloatField()),
                ('tipo_pago', models.CharField(max_length=255)),
                ('monto', models.FloatField()),
                ('cambio', models.FloatField()),
                ('pago', models.FloatField()),
                ('tipo_pedido', models.IntegerField(choices=[(1, 'Local'), (2, 'Domicilio'), (3, 'Recoger')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('tipo', models.IntegerField(choices=[(1, 'Gasto'), (2, 'Ganancia')])),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.ingresodiario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('notas', models.CharField(max_length=500)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.pedido')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_de_venta.platillo')),
            ],
        ),
    ]
