# Generated by Django 4.2 on 2024-04-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
