# Generated by Django 4.2 on 2024-04-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0003_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
