# Generated by Django 4.2 on 2024-04-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0004_alter_pedido_mesa_delete_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cambio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
