# Generated by Django 4.2.11 on 2024-04-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0006_pedido_nombre_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='monto_total',
        ),
    ]
