# Generated by Django 4.2.11 on 2024-04-08 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('punto_de_venta', '0007_remove_pedido_monto_remove_pedido_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
