# Generated by Django 4.2.11 on 2024-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0008_alter_pedido_created_by_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='notas',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
