# Generated by Django 4.2.11 on 2024-04-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0009_pedido_direccion_alter_detallepedido_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Listo'), (4, 'Entregado')], default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
