# Generated by Django 4.2.11 on 2024-05-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0010_alter_pedido_estado_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
