# Generated by Django 4.2.11 on 2024-05-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_de_venta', '0012_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
